---BUILD DATABASE AND SCHEMAS
CREATE OR REPLACE DATABASE FUDGEMART_DW;
USE DATABASE FUDGEMART_DW;

CREATE OR REPLACE SCHEMA STAGING;
CREATE OR REPLACE SCHEMA DIMENSIONS;
CREATE OR REPLACE SCHEMA FACTS;

USE DATABASE FUDGEMART_DW;
USE SCHEMA STAGING;

----CREATE STAGING TABLES WHERE I LOAD DATA 

CREATE OR REPLACE TABLE FM_CUSTOMERS (
    CUSTOMER_ID INT,
    CUSTOMER_EMAIL STRING,
    CUSTOMER_FIRSTNAME STRING,
    CUSTOMER_LASTNAME STRING,
    CUSTOMER_ADDRESS STRING,
    CUSTOMER_CITY STRING,
    CUSTOMER_STATE STRING,
    CUSTOMER_ZIP STRING,
    CUSTOMER_PHONE STRING,
    CUSTOMER_FAX STRING
);

CREATE OR REPLACE TABLE FM_ORDER_DETAILS (
    ORDER_ID INT,
    PRODUCT_ID INT,
    ORDER_QTY INT
);

CREATE OR REPLACE TABLE STAGING.FM_PRODUCTS (
    PRODUCT_ID INT,
    PRODUCT_DEPARTMENT STRING,
    PRODUCT_NAME STRING,
    PRODUCT_RETAIL_PRICE NUMBER(10,2),
    PRODUCT_WHOLESALE_PRICE NUMBER(10,2),
    PRODUCT_IS_ACTIVE STRING,
    PRODUCT_ADD_DATE DATE,
    PRODUCT_VENDOR_ID INT,
    PRODUCT_DESCRIPTION STRING
);

CREATE OR REPLACE TABLE FF_ACCOUNTS (
    ACCOUNT_ID INT,
    ACCOUNT_EMAIL STRING,
    ACCOUNT_FIRSTNAME STRING,
    ACCOUNT_LASTNAME STRING,
    ACCOUNT_ADDRESS STRING,
    ACCOUNT_ZIPCODE STRING,
    ACCOUNT_PLAN_ID INT,
    ACCOUNT_OPENED_ON DATE
);

CREATE OR REPLACE TABLE FF_ACCOUNT_BILLING (
    AB_ID INT,
    AB_DATE DATE,
    AB_ACCOUNT_ID INT,
    AB_PLAN_ID INT,
    AB_BILLED_AMOUNT NUMBER(10,2)
);

CREATE OR REPLACE TABLE FF_PLANS (
    PLAN_ID INT,
    PLAN_NAME STRING,
    PLAN_PRICE NUMBER(10,2),
    PLAN_CURRENT BOOLEAN
);

CREATE OR REPLACE TABLE STAGING.FM_ORDERS (
    ORDER_ID INT,
    CUSTOMER_ID INT,
    ORDER_DATE DATE,
    SHIPPED_DATE DATE,
    SHIP_VIA STRING,
    CREDITCARD_ID INT
);



----BUILDING DIMENSION TABLES

CREATE OR REPLACE TABLE DIMENSIONS.DIM_CUSTOMER (
    CUSTOMER_KEY INTEGER AUTOINCREMENT,
    CUSTOMER_ID INTEGER,
    SOURCE_SYSTEM VARCHAR,
    CUSTOMER_FIRSTNAME VARCHAR,
    CUSTOMER_LASTNAME VARCHAR,
    CUSTOMER_EMAIL VARCHAR
);

--FUDGEMART CUSTOMERS
INSERT INTO DIMENSIONS.DIM_CUSTOMER (
    CUSTOMER_ID,
    SOURCE_SYSTEM,
    CUSTOMER_FIRSTNAME,
    CUSTOMER_LASTNAME,
    CUSTOMER_EMAIL
)
SELECT
    CUSTOMER_ID,
    'fudgemart',
    CUSTOMER_FIRSTNAME,
    CUSTOMER_LASTNAME,
    CUSTOMER_EMAIL
FROM STAGING.FM_CUSTOMERS;
---FUDGEFLIX ACCOUNTS
INSERT INTO DIMENSIONS.DIM_CUSTOMER (
    CUSTOMER_ID,
    SOURCE_SYSTEM,
    CUSTOMER_FIRSTNAME,
    CUSTOMER_LASTNAME,
    CUSTOMER_EMAIL
)
SELECT
    ACCOUNT_ID,
    'fudgeflix',
    ACCOUNT_FIRSTNAME,
    ACCOUNT_LASTNAME,
    ACCOUNT_EMAIL
FROM STAGING.FF_ACCOUNTS;

SELECT * FROM DIMENSIONS.DIM_CUSTOMER LIMIT 10;

CREATE OR REPLACE TABLE DIMENSIONS.DIM_PRODUCT (
    PRODUCT_KEY INTEGER AUTOINCREMENT,
    PRODUCT_ID INTEGER,
    PRODUCT_NAME VARCHAR,
    PRODUCT_PRICE NUMBER(10,2),
    PRODUCT_TYPE VARCHAR
);
--FUDGEMART PRODUCTS

INSERT INTO DIMENSIONS.DIM_PRODUCT (
    PRODUCT_ID,
    PRODUCT_NAME,
    PRODUCT_PRICE,
    PRODUCT_TYPE
)
SELECT DISTINCT
    PRODUCT_ID,
    PRODUCT_NAME,
    PRODUCT_RETAIL_PRICE,
    'fudgemart'
FROM STAGING.FM_PRODUCTS;

---FUDGEFLIX PRODUCTS
INSERT INTO DIMENSIONS.DIM_PRODUCT (
    PRODUCT_ID,
    PRODUCT_NAME,
    PRODUCT_PRICE,
    PRODUCT_TYPE
)
SELECT DISTINCT
    PLAN_ID,
    PLAN_NAME,
    PLAN_PRICE,
    'fudgeflix'
FROM STAGING.FF_PLANS;

SELECT * FROM DIMENSIONS.DIM_PRODUCT LIMIT 10;

CREATE OR REPLACE TABLE DIMENSIONS.DIM_DATE (
    DATE_KEY BIGINT AUTOINCREMENT,
    DATE_ORDERDATEID DATE,
    DATE_QUARTER INT,
    DATE_YEAR INT,
    DATE_MONTH INT,
    DATE_DAY INT
);
---FUDGEMART DATE
INSERT INTO DIMENSIONS.DIM_DATE (
    DATE_ORDERDATEID,
    DATE_QUARTER,
    DATE_YEAR,
    DATE_MONTH,
    DATE_DAY
)
SELECT DISTINCT
    ORDER_DATE,
    QUARTER(ORDER_DATE),
    YEAR(ORDER_DATE),
    MONTH(ORDER_DATE),
    DAY(ORDER_DATE)
FROM STAGING.FM_ORDERS
WHERE ORDER_DATE IS NOT NULL;
---FUDGEFLIX DATE
INSERT INTO DIMENSIONS.DIM_DATE (
    DATE_ORDERDATEID,
    DATE_QUARTER,
    DATE_YEAR,
    DATE_MONTH,
    DATE_DAY
)
SELECT DISTINCT
    AB_DATE,
    QUARTER(AB_DATE),
    YEAR(AB_DATE),
    MONTH(AB_DATE),
    DAY(AB_DATE)
FROM STAGING.FF_ACCOUNT_BILLING
WHERE AB_DATE IS NOT NULL
AND AB_DATE NOT IN (
    SELECT DATE_ORDERDATEID
    FROM DIMENSIONS.DIM_DATE
);

SELECT * FROM DIMENSIONS.DIM_DATE LIMIT 20;

---BUILD FACT_SALES TABLE
CREATE OR REPLACE TABLE FACTS.FACT_SALES (
    SALES_KEY INTEGER AUTOINCREMENT,
    SALES_PRODUCTPRICE NUMBER(10,2),
    SALES_QUANTITY INTEGER,
    SALES_TOTAL NUMBER(10,2),
    SALES_CUSTOMERKEY INTEGER,
    SALES_ORDERDATEKEY INTEGER,
    SALES_PRODUCTKEY INTEGER
);

---FUDGEMART INSERT
INSERT INTO FACTS.FACT_SALES (
    SALES_PRODUCTPRICE,
    SALES_QUANTITY,
    SALES_TOTAL,
    SALES_CUSTOMERKEY,
    SALES_ORDERDATEKEY,
    SALES_PRODUCTKEY
)
SELECT
    p.PRODUCT_RETAIL_PRICE,
    od.ORDER_QTY,
    od.ORDER_QTY * p.PRODUCT_RETAIL_PRICE,
    dc.CUSTOMER_KEY,
    dd.DATE_KEY,
    dp.PRODUCT_KEY
FROM STAGING.FM_ORDERS o
JOIN STAGING.FM_ORDER_DETAILS od
    ON o.ORDER_ID = od.ORDER_ID
JOIN STAGING.FM_PRODUCTS p
    ON od.PRODUCT_ID = p.PRODUCT_ID
JOIN DIMENSIONS.DIM_CUSTOMER dc
    ON dc.CUSTOMER_ID = o.CUSTOMER_ID
   AND dc.SOURCE_SYSTEM = 'fudgemart'
JOIN DIMENSIONS.DIM_PRODUCT dp
    ON dp.PRODUCT_ID = od.PRODUCT_ID
   AND dp.PRODUCT_TYPE = 'fudgemart'
JOIN DIMENSIONS.DIM_DATE dd
    ON dd.DATE_ORDERDATEID = o.ORDER_DATE;

---FUDGEFLIX INSERT
INSERT INTO FACTS.FACT_SALES (
    SALES_PRODUCTPRICE,
    SALES_QUANTITY,
    SALES_TOTAL,
    SALES_CUSTOMERKEY,
    SALES_ORDERDATEKEY,
    SALES_PRODUCTKEY
)
SELECT
    pl.PLAN_PRICE,
    1,
    ab.AB_BILLED_AMOUNT,
    dc.CUSTOMER_KEY,
    dd.DATE_KEY,
    dp.PRODUCT_KEY
FROM STAGING.FF_ACCOUNT_BILLING ab
JOIN STAGING.FF_PLANS pl
    ON ab.AB_PLAN_ID = pl.PLAN_ID
JOIN DIMENSIONS.DIM_CUSTOMER dc
    ON dc.CUSTOMER_ID = ab.AB_ACCOUNT_ID
   AND dc.SOURCE_SYSTEM = 'fudgeflix'
JOIN DIMENSIONS.DIM_PRODUCT dp
    ON dp.PRODUCT_ID = ab.AB_PLAN_ID
   AND dp.PRODUCT_TYPE = 'fudgeflix'
JOIN DIMENSIONS.DIM_DATE dd
    ON dd.DATE_ORDERDATEID = ab.AB_DATE;

---VALIDATION CHECKS
SELECT COUNT(*) FROM FACTS.FACT_SALES;
SELECT COUNT(*) FROM STAGING.FM_ORDER_DETAILS;
SELECT COUNT(*) FROM STAGING.FF_ACCOUNT_BILLING;
---FACT_SALES COUNT LINES UP WITH TOTAL FROM FM_ORDER_DETAILS AND FF_ACCOUNT_BILLING
SELECT * FROM FACTS.FACT_SALES LIMIT 20;
SELECT MIN(SALES_TOTAL), MAX(SALES_TOTAL), SUM(SALES_TOTAL) FROM FACTS.FACT_SALES;

SELECT *
FROM FACTS.FACT_SALES
ORDER BY SALES_TOTAL DESC
LIMIT 10;
---CHECKING JOINS
SELECT COUNT(*) AS matched_rows
FROM FACTS.FACT_SALES fs
JOIN DIMENSIONS.DIM_CUSTOMER dc
    ON fs.SALES_CUSTOMERKEY = dc.CUSTOMER_KEY;

SELECT COUNT(*) AS matched_rows
FROM FACTS.FACT_SALES fs
JOIN DIMENSIONS.DIM_PRODUCT dp
    ON fs.SALES_PRODUCTKEY = dp.PRODUCT_KEY;

SELECT COUNT(*) AS matched_rows
FROM FACTS.FACT_SALES fs
JOIN DIMENSIONS.DIM_DATE dd
    ON fs.SALES_ORDERDATEKEY = dd.DATE_KEY;

SELECT COUNT(*) AS matched_rows
FROM FACTS.FACT_SALES fs
JOIN DIMENSIONS.DIM_CUSTOMER dc
    ON fs.SALES_CUSTOMERKEY = dc.CUSTOMER_KEY
JOIN DIMENSIONS.DIM_PRODUCT dp
    ON fs.SALES_PRODUCTKEY = dp.PRODUCT_KEY
JOIN DIMENSIONS.DIM_DATE dd
    ON fs.SALES_ORDERDATEKEY = dd.DATE_KEY;

--NO NULLS
SELECT COUNT(*) AS missing_customers
FROM FACTS.FACT_SALES fs
LEFT JOIN DIMENSIONS.DIM_CUSTOMER dc
    ON fs.SALES_CUSTOMERKEY = dc.CUSTOMER_KEY
WHERE dc.CUSTOMER_KEY IS NULL;

SELECT COUNT(*) AS missing_products
FROM FACTS.FACT_SALES fs
LEFT JOIN DIMENSIONS.DIM_PRODUCT dp
    ON fs.SALES_PRODUCTKEY = dp.PRODUCT_KEY
WHERE dp.PRODUCT_KEY IS NULL;

SELECT COUNT(*) AS missing_dates
FROM FACTS.FACT_SALES fs
LEFT JOIN DIMENSIONS.DIM_DATE dd
    ON fs.SALES_ORDERDATEKEY = dd.DATE_KEY
WHERE dd.DATE_KEY IS NULL;
